- name: Install required packages
  ansible.builtin.apt:
    # required for lddtree
    name:
      - pax-utils
      - flex
      - bison
      - libelf-dev
      - libssl-dev
  become: true

- name: Clone required submodules
  # noqa: command-instead-of-module
  ansible.builtin.command: >-
    git submodule update --init --depth 200
    --jobs {{ ansible_processor_nproc }}
    {{ dvkm_sub_path }}
    {{ linux_agent_sub_path }}
  args:
    chdir: "{{ examples_root }}"
